# 5 interesting Pytorch - Tensor functions



An short introduction about PyTorch and about the chosen functions. 
- torch.arange
- torch.normal
- torch.reshape
- torch.sort
- torch.unfold


In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.arange

Returns a 1-D tensor of size ((end - start)/step)
​with values from the interval [start, end) taken with common difference step beginning from start.

Basic parameters :
- start (Number) – the starting value for the set of points. Default: 0.

- end (Number) – the ending value for the set of points

- step (Number) – the gap between each pair of adjacent points. Default:1.

In [2]:
# Example 1 - working 
torch.arange(2, 5)

tensor([2, 3, 4])

start = 2 , end = 5 , step = 1(Default) , so the output must be
a tensor with values (2,2+1,2+1+1) 

In [3]:
# Example 2 - working
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

Since its a tensor -> Single Data Type then all elements will be floats
start = 1.0 , end = 2.5 step = 0.5 so the output must be
a tensor with values (1.0,1.0+0.5,1.0+0.5+0.5) 

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(3, 2)

RuntimeError: ignored

Error because start>end and step >0

Use it to get an 1-D tensor with desirable pattern

## Function 2 - torch.normal

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

Basic Parameters:
- mean (Tensor) – the tensor of per-element means

- std (Tensor) – the tensor of per-element standard deviations

In [5]:
# Example 1 - working
torch.normal(2, 3, size=(1, 4))

tensor([[-2.6948,  4.7232, -4.1147, -0.4934]])

Each element comes from a normal distribution with :

mean = 2, std = 3

Size will be a 1-D tensor with 4 elements

In [6]:
# Example 2 - working
torch.normal(mean=torch.arange(0.0,3.0), std=torch.arange(0, 0.3, 0.1))

tensor([0.0000, 0.9798, 1.8692])

Each element comes from a normal distribution with :

mean = [0,1,2] , std = [0,0.1,0.2]

Size will be a 1-D tensor with 3 elements

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=torch.arange(0.0,3.0), std=torch.arange(0, 0.3, 0.2))

RuntimeError: ignored

mean and std must have the same size !

Use it when u want a initialized tensor , useful for bias and weights

## Function 3 - torch.reshape

Returns a tensor with the same data and number of elements as input, but with the specified shape.

Basic Parameters:
- input (Tensor) – the tensor to be reshaped

- shape (tuple of python:ints) – the new shape

A single dimension may be -1, in which case it’s inferred from the remaining dimensions and the number of elements in input.

In [17]:
# Example 1 - working
a = torch.tensor([[0, 1], [2, 3]])
a=torch.reshape(a, (4, 1))
print(a)
a.size()

tensor([[0],
        [1],
        [2],
        [3]])


torch.Size([4, 1])

We define a [2,2] tensor and reshape it to a [4,1] tensor

In [18]:
# Example 2 - working
a = torch.arange(4.)
a=torch.reshape(a,(2,-1))
print(a)
a.size()

tensor([[0., 1.],
        [2., 3.]])


torch.Size([2, 2])

We define a Tensor with size [4] and reshape it to [2,-1] , -1 must fit so in this case -1=2

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.arange(4.)
a=torch.reshape(a,(3,-1))

RuntimeError: ignored

[3,-1] is invalid , there is no valid value for -1 

Use it to reshape tensors


## Function 4 - torch.sort

Sorts the elements of the input tensor along a given dimension in ascending order by value.

Basic Parameters:
- input (Tensor) – the input tensor.

- dim (int, optional) – the dimension to sort along

- descending (bool, optional) – controls the sorting order (ascending or descending)


A namedtuple of (values, indices) is returned, where the values are the sorted values and indices are the indices of the elements in the original input tensor.

In [20]:
# Example 1 - working
a=torch.arange(-2, -5,-1)
sorted, indices = torch.sort(a)
print(sorted)
print(indices)

tensor([-4, -3, -2])
tensor([2, 1, 0])


We sort [-2,-3,-4] 

descending=False

In [21]:
# Example 2 - working
a=torch.arange(2, 5)
sorted, indices = torch.sort(a,descending=True)
print(sorted)
print(indices)

tensor([4, 3, 2])
tensor([2, 1, 0])


We sort [2,3,4] 

descending=True

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[0, 1], [2, 3]])
sorted, indices = torch.sort(a,dim=2)


IndexError: ignored

Dimension parameter is not valid , valid values=[-2,-1,0,1]

Use it to sort tensors

## Function 5 - torch.unfold

Returns a view of the original tensor which contains all slices of size size from self tensor in the dimension dimension.

Step between two slices is given by step.

If sizedim is the size of dimension dimension for self, the size of dimension dimension in the returned tensor will be (sizedim - size) / step + 1.

Basic parameters:
- dimension (int) – dimension in which unfolding happens

- size (int) – the size of each slice that is unfolded

- step (int) – the step between each slice

In [23]:
# Example 1 - working
x = torch.tensor([0,1,2,3,4,5])
x.unfold(0, 2, 1)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5]])

Its a form of reshape , each slise has size 2 and with step 1 we go from [0,1]->[1,2] etc

In [24]:
# Example 2 - working
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.unfold(1, 2, 2)

tensor([[[1, 2]],

        [[4, 5]]])

With step = 2 and size = 2 and dim = 1 we skip one value , which cannot be obtained

In [25]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.unfold(1, 4, 2)

RuntimeError: ignored

Size of the slice must be valid 

Use it when you want to transform your tensor using the existing elements

## Conclusion

We explored some interesting pytorch function , which can be used in the future in order to create valid tensors for our deep neural networks

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html